###########################################################################
# Copyrights ï¿½ 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
#########################################################################
openapi: 3.0.2
info:
  title: SnapPay
  description: Digitally transform your payment process with certified ERP integration to improve working capital and increase efficiencies. SnapPay from Fiserv, integrates with popular ERP solutions and shopping cart solutions to serve the holistic B2B payment needs of enterprise-size businesses.
  version: 1.0.0
servers:
  - url: https://restapi.snappayglobal.com/
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
tags:
  - name: APIs with User Interaction
  - name: APIs without User Interaction
  - name: Card Account Updater
paths:
  /api/interop/GetRequestID:
    post:
      tags:
        - APIs with User Interaction
      x-group-name: APIs with User Interaction
      x-proxy-name: Get Request ID
      summary: Get Request ID - Field Level
      description: Get request ID.
      operationId: getRequestID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accountid:
                  description: Account ID
                  type: number
                  example: 1000000001
                companycode:
                  description: Company Code
                  type: string
                  example: 00200
                currencycode: 
                  description: Currency Code
                  type: string
                  example: USD
                customerid: 
                  description: Customer ID
                  type: string
                  example: 100
                userid: 
                  description: External Application User ID
                  type: string
                  example: johnsmith@abc.com
                transactiontype:
                  description: S - for Sale
                  type: string
                  example: S
                paymentmethod:
                  description: CC - for credit card
                  type: string
                  example: CC
                language:
                  description: en-US for English language
                  type: string
                  example: en-US
                stylecss:
                  description: CSS properties separated by semicolon. List is given below under Supported CSS Properties.
                  type: string
                  example: border:2px solid orange;
                savepaymentmethod: 
                  description: Save payment method for future use
                  type: string
                  example: Y
                redirecturl: 
                  description: en-US for English language
                  type: string
                  example: https://xyz.com/orderconfirmation
                transactionamount: 
                  description: Transaction Amount
                  type: number
                  example: 100.25
                cvvrequired: 
                  description: Credit Card Security Code
                  type: string
                  example: Y
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
      responses:
        '200':
          description: Request successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  accountid:
                    type: number
                    description: Account ID
                    example: 1000000008
                  token:
                    type: string
                    description: Request ID that will be used to open SnapPay iFrame
                    example: 0b724a4f-5bbb-e811-b229-000c29cce4c0
                  status:
                    type: string
                    description: Y or N
                    example: 'Y'
                  message:
                    type: string
                    description: e.g. Information stored successfully
                    example: Information stored successfully.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /api/Interop/GetPaymentDetails:
    post:
      tags:
        - APIs with User Interaction
      x-group-name: APIs with User Interaction
      x-proxy-name: Get Payment Details
      summary: Get Payment Details
      description: Get Payment Details.
      operationId: getPaymentDetails
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountid: '1000000001'
                token: 073c8be3-b0db-e811-a954-000d3a92a01e
      security:
        - basicAuth: []
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
      responses:
        '200':
          description: Request successful.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /api/interop/tokenize:
    post:
      tags:
        - APIs without User Interaction
      x-group-name: APIs without User Interaction
      x-proxy-name: Tokenize
      summary: Tokenize
      description: Tokenize.
      operationId: tokenize
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountid: 1000000001
                requesttype: C
                currency: USD
                companycode: '00200'
                branchplant: ''
                ordertype: ''
                mode: CC
                type: VISA
                routingnumber: ''
                bankname: ''
                checktype: ''
                identificationtype: ''
                dlstate: ''
                identificationnumber: ''
                accountnumber: 16 digit card number
                expirationdate: '042020'
                name: ABC Customer
                addressline1: Main Street
                city: Aurora
                state: IL
                zip: '60540'
                country: US
                email: noreply@snappay.com
                phonenumber: ''
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
      responses:
        '200':
          description: Request successful.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /api/interop/authorize:
    post:
      tags:
        - APIs without User Interaction
      x-group-name: APIs without User Interaction
      x-proxy-name: Authorize
      summary: Authorize
      description: Authorize.
      operationId: authorize
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountid: 1000000001
                customerid: '100'
                currency: USD
                companycode: '00200'
                branchplant: ''
                ordertype: ''
                orderid: ''
                invoiceid: '10093'
                userid: user1
                reference: ''
                purchaseorder: ''
                cards:
                  - transactionamount: 10
                    tokenid: '9417085548851111'
                    cvv: ''
                    expirationdate: '042023'
                    customername: ABC Customer
                    addressline1: Main street
                    city: Aurora
                    state: IL
                    zip: '60540'
                    country: US
                    email: noreply@snappay.com
                    phonenumber: ''
                    type: VISA
                    last4: '1111'
      security:
        - basicAuth: []
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
      responses:
        '200':
          description: Request successful.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /api/interop/charge:
    post:
      tags:
        - APIs without User Interaction
      x-group-name: APIs without User Interaction
      x-proxy-name: Charge
      summary: Charge
      description: Charge.
      operationId: charge
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountid: '1000000001'
                referencetransactionid: '1329'
                transactionamount: '500'
                customerid: '4242'
                currency: USD
                companycode: '00200'
                userid: noreply@snappay.com
                orderid: '123'
                invoiceid: '123'
                customid: ''
                comment: Capture for Order 123
                sendemailreceipts: 'Y'
                level3:
                  - linenumber: '001'
                    productcode: BQT01
                    unitcost: '1.75'
                    quantity: '3'
                    itemdescriptor: Bouquet
                    unitofmeasure: EA
                    commoditycode: Commodity 1
                    taxamount: '0.12'
                    taxrate: '8'
                    itemdiscount: '0'
                    lineitemtotal: '5.37'
                  - linenumber: '002'
                    productcode: BQT02
                    unitcost: '2'
                    quantity: '3'
                    itemdescriptor: Bouquet
                    unitofmeasure: EA
                    commoditycode: Commodity 2
                    taxamount: '0.97'
                    taxrate: '8'
                    itemdiscount: '0'
                    lineitemtotal: '6.97'
      security:
        - basicAuth: []
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
      responses:
        '200':
          description: Request successful.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /api/Interop/Capture:
    post:
      tags:
        - APIs without User Interaction
      x-group-name: APIs without User Interaction
      x-proxy-name: Capture
      summary: Capture
      description: Capture.
      operationId: capture
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountid: '1000000001'
                companycode: '00100'
                shipfromzip: '60500'
                branchplant: M30
                orderid: '123448'
                invoiceid: '567848'
                orderdate: ''
                userid: userid1
                shiptocountry: ''
                purchaseorder: '1243'
                shiptozip: ''
                customerid: '4242'
                currency: USD
                sendemailreceipts: 'Y'
                ecomind: E
                cof: C
                cofscheduled: 'N'
                paymentmethod:
                  tokenid: '100672315657'
                  transactionamount: '125.50'
                  cvv: '123'
                  customername: Hex Financial
                  addressline1: Main Street
                  city: Aurora
                  state: IL
                  zip: '60540'
                  country: US
                  email: noreply@snappay.com
                  phonenumber: ''
                  type: checking
                  last4: '6789'
                  routingnumber: '123123123'
                  secureflag: '05'
                  securevalue: ''
                  securedstid: ''
                  secureexemption: lowvalue
                level3:
                  - linenumber: '1.000'
                    productcode: ROS01
                    taxrate: '0.073'
                    quantity: '2'
                    itemdescriptor: Mixed Bouquet
                    unitcost: '30.7500'
                    lineitemtotal: '65.96'
                    taxamount: '4.46'
                    commoditycode: Commodity 1
                    unitofmeasure: EA
                  - linenumber: '2.000'
                    productcode: BQT02
                    taxrate: '0.073'
                    quantity: '2'
                    itemdescriptor: Spring Bouquet
                    unitcost: '25.6250'
                    lineitemtotal: '54.97'
                    taxamount: '3.72'
                    commoditycode: Commodity 2
                    unitofmeasure: EA
                ordertype: SO
                userfields:
                  - udf0: Value 1
                  - udf1: Value 2
                  - udf2: Value 3
                  - udf3: Value 4
                  - custommerchant: Your Company
                  - customphone: 888-555-HELP
      security:
        - basicAuth: []
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
      responses:
        '200':
          description: Request successful.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /api/Interop/Credit:
    post:
      tags:
        - APIs without User Interaction
      x-group-name: APIs without User Interaction
      x-proxy-name: Credit
      summary: Credit
      description: Credit.
      operationId: credit
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountid: 1000000001
                customerid: '100'
                currency: USD
                companycode: '00100'
                userid: User1
                orderid: '123'
                invoiceid: '423'
                ordertype: ''
                branchplant: ''
                reference: ''
                purchaseorder: ''
                sendemailreceipts: 'Y'
                ecomind: E
                cof: C
                cofscheduled: 'N'
                paymentmethod:
                  transactionamount: '12.34'
                  tokenid: '9548009641895454'
                  secureflag: '05'
                  securevalue: ''
                  securedstid: ''
                  secureexemption: lowvalue
                userfields:
                  - udf0: Value 1
                  - udf1: Value 2
                  - udf2: Value 3
                  - udf3: Value 4
                  - custommerchant: Fiserv Company
                  - customphone: 888-555-HELP
      security:
        - basicAuth: []
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
      responses:
        '200':
          description: Request successful.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /api/Interop/Refund:
    post:
      tags:
        - APIs without User Interaction
      x-group-name: APIs without User Interaction
      x-proxy-name: Refund
      summary: Refund
      description: Refund.
      operationId: refund
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountid: 1000000001
                referencetransactionid: '1403'
                transactionamount: '10.00'
                customerid: '100'
                currency: USD
                companycode: '00100'
                userid: User
                orderid: '123'
                invoiceid: '423'
                reference: ''
                purchaseorder: ''
                sendemailreceipts: 'Y'
      security:
        - basicAuth: []
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
      responses:
        '200':
          description: Request successful.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /api/Interop/Void:
    post:
      tags:
        - APIs without User Interaction
      x-group-name: APIs without User Interaction
      x-proxy-name: Void
      summary: Void
      description: The Void API attempts to void or cancel a prior authorization transaction. The original authorization transaction is set in parameter referencetransactionid and some explanatory text can be set in the reference parameter. For voding charge and capture transaction, use refund API.
      operationId: void
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountid: 1000000001
                referencetransactionid: '1458'
                customerid: '100'
                currency: USD
                companycode: '00100'
                userid: User
                reference: ''
                purchaseorder: ''
      security:
        - basicAuth: []
      parameters:
        - name: AccountId
          in: header
          schema:
            type: integer
          example: '1000000001'
        - name: merchantid
          in: header
          schema:
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
      responses:
        '200':
          description: Request successful.
          content:
            application/json: {}
  /api/interop/GetTransaction:
    post:
      tags:
        - APIs without User Interaction
      x-group-name: APIs without User Interaction
      x-proxy-name: Get Transaction
      summary: GetTransaction
      description: GetTransactionRequest
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountid: '1000000001'
                transactionid: '3664'
                orderid: '123'
      security:
        - basicAuth: []
      parameters:
        - name: AccountId
          in: header
          schema:
            type: integer
          example: '1000000001'
        - name: merchantid
          in: header
          schema:
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/TransactionHistory:
    get:
      tags:
        - APIs without User Interaction
      x-group-name: APIs without User Interaction
      x-proxy-name: Retrieve Transaction History
      summary: Retrieve Transaction History
      description: Retrieve Transaction History.
      operationId: retrieveTransactionHistory
      security:
        - basicAuth: []
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
        - name: startdate
          in: query
          schema:
            type: string
          example: '{{startdate}}'
        - name: enddate
          in: query
          schema:
            type: string
          example: '{{enddate}}'
        - name: type
          in: query
          schema:
            type: string
          example: C
      responses:
        '200':
          description: Request successful.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /api/FundingHistory:
    get:
      tags:
        - APIs without User Interaction
      x-group-name: APIs without User Interaction
      x-proxy-name: Retrieve Funding History
      summary: Retrieve Funding History
      description: Retrieve Funding History.
      operationId: retrieveFundingHistory
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
        - name: startdate
          in: query
          schema:
            type: string
          example: '{{startdate}}'
        - name: enddate
          in: query
          schema:
            type: string
          example: '{{enddate}}'
      responses:
        '200':
          description: Request successful.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /api/binapi/MID/token:
    get:
      tags:
        - APIs without User Interaction
      x-group-name: APIs without User Interaction
      x-proxy-name: Bin Information
      summary: Bin Information
      description: Bin Information.
      operationId: binInformation
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
      responses:
        '200':
          description: Request successful.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /AccountUpdater/GetUpdater:
    post:
      tags:
        - Card Account Updater
      x-group-name: Card Account Updater
      x-proxy-name: Get Updater
      summary: Get Updater
      description: Get Updater.
      operationId: getUpdater
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                merchid: MID
                accounts:
                  - account: '4111111111111111'
                    expiry: '0122'
                  - account: '9434567891111111'
                    expiry: '0525'
      security:
        - basicAuth: []
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
      responses:
        '200':
          description: Request successful.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /AccountUpdater/PutUpdater:
    post:
      tags:
        - Card Account Updater
      x-group-name: Card Account Updater
      x-proxy-name: Put Updater
      summary: Put Updater
      description: Put Updater.
      operationId: putUpdater
      security:
        - basicAuth: []
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
          example: 'optional '
        - name: Signature
          in: header
          schema:
            type: string
          example: HMAC <<unique hmac value>>
        - name: merchid
          in: query
          schema:
            type: string
          example: MID
        - name: date
          in: query
          schema:
            type: integer
          example: '20220131'
      responses:
        '200':
          description: Request successful.
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.
  /AccountUpdater/DeleteUpdater:
    post:
      tags:
        - Card Account Updater
      x-group-name: Card Account Updater
      x-proxy-name: Delete Updater
      summary: DeleteUpdater
      description: The DELETE request unenrolls accounts that have been manually added using the PUT method.
      operationId: deleteUpdater
      parameters:
        - name: AccountId
          in: header
          description: Account ID
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: number
        - name: MerchantId
          in: header
          description: Merchant ID (if you pass this parameter, SnapPay will bypass the logic of identifying MID for this transaction)
          schema:
            maxLength: 50
            minLength: 0
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchid:
                  description: Merchant ID
                  nullable: false
                  type: number
                  example: 496695144562
                accounts:
                  description: List of Credit Card Tokens that need to be deleted
                  nullable: false
                  type: array
                  items:
                    type: number
                  example:
                    - 9417085548851112
                    - 9550096877584444
              additionalProperties: false
      responses:
        '200':
          description: Request successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  merchid:
                    type: number
                    description: Merchant ID
                    example: 496695144562
                  total:
                    type: number
                    description: Total tokens received
                    example: 2
                  deleted:
                    type: number
                    description: Number of tokens that were deleted successfully
                    example: 1
                  notdeleted:
                    type: array
                    items:
                      type: object
                      properties:
                        account:
                          type: string
                          description: The token that caused the error
                          example: 9550096877584444
                        message:
                          type: string
                          description: Error message
                          example: account/token does not exist in CAU database
        '400':
          description: Invalid request.
        '401':
          description: Unauthorized access.
        '500':
          description: Internal server error.

